### ISSUE TITLE
Crash with latest RLCraft

### ISSUE THREAD

**Issue by Ski-z** [fonnymunkey/RLMixins#1]
https://hastebin.com/wobefelomi.yaml

**Comment by Ski-z** [comment]
// There are four lights!

Time: 12/20/22 2:48 PM
Description: Unexpected error

java.lang.NoSuchMethodError: meldexun.reachfix.util.ReachFixUtil.getBlockReach(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/EnumHand;)D
	at com.creativemd.itemphysic.EventHandler.handler$zgd000$rlmixins_itemPhysicsEventHandler_getReachDistance(EventHandler.java:522)
	at com.creativemd.itemphysic.EventHandler.getReachDistance(EventHandler.java)
	at com.creativemd.itemphysic.EventHandler.getEntityItem(EventHandler.java:114)
	at com.creativemd.itemphysic.EventHandler.renderTickFull(EventHandler.java:227)
	at com.creativemd.itemphysic.EventHandler.renderTick(EventHandler.java:316)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1562_EventHandler_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:360)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1123)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.itemphysic.EventHandler.handler$zgd000$rlmixins_itemPhysicsEventHandler_getReachDistance(EventHandler.java:522)
	at com.creativemd.itemphysic.EventHandler.getReachDistance(EventHandler.java)
	at com.creativemd.itemphysic.EventHandler.getEntityItem(EventHandler.java:114)
	at com.creativemd.itemphysic.EventHandler.renderTickFull(EventHandler.java:227)
	at com.creativemd.itemphysic.EventHandler.renderTick(EventHandler.java:316)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1562_EventHandler_renderTick_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Ski_'/1003, l='MpServer', x=2501.50, y=33.00, z=736.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-72,64,84), Chunk: (at 8,4,4 in -5,5; contains blocks -80,0,80 to -65,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 13 game time, 13 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityLatchedRenderer['unknown'/2210, l='MpServer', x=8.50, y=65.00, z=8.50], EntityPlayerSP['Ski_'/1003, l='MpServer', x=2501.50, y=33.00, z=736.50]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/2210, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_312, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 786589512 bytes (750 MB) / 2488795136 bytes (2373 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -Xmx4096m -Xms4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 171 mods loaded, 171 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by Ski-z** [comment]
When I delete Item Physics, I get this:

Time: 12/20/22 3:19 PM
Description: Unexpected error

java.lang.NoSuchMethodError: meldexun.reachfix.hook.client.EntityRendererHook.pointedObject(Lnet/minecraft/entity/Entity;Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/util/EnumHand;Lnet/minecraft/world/World;F)Lnet/minecraft/util/math/RayTraceResult;
	at bettercombat.mod.client.handler.EventHandlersClient.onMouseLeftClick(EventHandlersClient.java:81)
	at bettercombat.mod.client.handler.EventHandlersClient.onMouseEvent(EventHandlersClient.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1334_EventHandlersClient_onMouseEvent_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:273)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2275)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1800)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at bettercombat.mod.client.handler.EventHandlersClient.onMouseLeftClick(EventHandlersClient.java:81)
	at bettercombat.mod.client.handler.EventHandlersClient.onMouseEvent(EventHandlersClient.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1334_EventHandlersClient_onMouseEvent_MouseEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:273)
	at net.minecraft.client.Minecraft.func_184124_aB(Minecraft.java:2275)

-- Affected level --

**Comment by fonnymunkey** [comment]
RLMixins currently relies on the latest version of ReachFix which hasn't been uploaded to Curseforge yet.
Currently testing of RLCraft 2.9.2 Alpha through the RLCraft discord has this latest version, hopefully soon it will be uploaded to Curseforge.

**Comment by fonnymunkey** [comment]
Latest ReachFix has been uploaded to Curseforge, updating will resolve this.
