### ISSUE TITLE
Rustic's `Ale` crash + dupe

### ISSUE THREAD

**Issue by Krutoy242** [fonnymunkey/RLMixins#25]
Steps and video to reproduce below alongside single player crash report - Only SOMETIMES works in singleplayer.

1. Make an Ale quality greater than 0.5
2. Have the item you're wanting to duplicate and the Ale in your inventory
3. Disconnect and Reconnect to save your player data
4. Put the item you're wanting to duplicate in a storage container
5. Drink the Ale (Force Disconnects you from the server for Internal Server Error)
6. Reconnect to the server/World
7. Done

## https://youtu.be/0pE7-0xSxP8

Crash log:
```ruby
java.lang.NullPointerException: Ticking player
    at net.minecraft.entity.EntityLivingBase.onNewPotionEffect(EntityLivingBase.java:807)
    at net.minecraft.entity.player.EntityPlayerMP.onNewPotionEffect(EntityPlayerMP.java:1186)
    at net.minecraft.entity.EntityLivingBase.addPotionEffect(EntityLivingBase.java:751)
    at rustic.common.blocks.fluids.ModFluids$Anonymous$56dfa75b9d574b48bdeb0dbee12f18d1.affectPlayer(ModFluidsMixin.java:46)
    at rustic.common.blocks.fluids.FluidBooze.onDrank(FluidBooze.java:35)
    at rustic.common.items.ItemFluidBottle.onItemUseFinish(ItemFluidBottle.java:110)
    at net.minecraft.item.ItemStack.onItemUseFinish(ItemStack.java:222)
```
Log: https://mclo.gs/ZRgp7Dm
RLMixin config: https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/v1.45.0/config/rlmixins.cfg

**Comment by fonnymunkey** [comment]
You have ale set as giving a lycanitemob's effect in the rlmixin config, but don't have lycanitemobs installed.
Change the ale effect to a potion effect you actually have in the pack.

**Comment by Krutoy242** [comment]
Oh, gotcha!
Would be great if unexisting potions not crashing game through 😅

**Comment by fonnymunkey** [comment]
The config that enables those changes is off by default, and the only reason for enabling it is to modify the drinks and what potion effect/timers they have, so the expectation is if you are enabled that change you are also modifying what effects it gives.
